### ISSUE TITLE
Possible issue with setup defaults?

### ISSUE THREAD

**Issue by shrike71** [fief-dev/fief#6]
Hi,

Followed the self-hosted docker instructions, supplemented with the information in the quick-start combined with the info in the "self-hosted" section to create a docker-compose file (below), to run an evaluation on a virtualbox controlled VM running ubuntu 21.04. I can't run the app on port 8000 on this set of stacks as I have another application running on it.

```
version: "3.9"

services:
  fief:
    container_name: fief
    hostname: fief
    image: ghcr.io/fief-dev/fief:latest
    ports:
      - "8001:8000"
    environment:
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_URL=postgresql://postgres:postgres@postgres-eval_db_1:5432/fief
      - SECRET=XXX
      - FIEF_CLIENT_ID=XXX
      - FIEF_CLIENT_SECRET=XXX
      - ENCRYPTION_KEY=XXX
      - FIEF_DOMAIN=ingress.local:8001
      - FIEF_BASE_URL=http://ingress.local:8001
    volumes:
      - fief-server-data:/data
    restart: unless-stopped
    networks:
      - eval

volumes:
  fief-server-data:
    external: true

networks:
  eval:
    external: true
```

With the information provided, the fief application DOES seem to set up successfully, with the appropriate schemas created and populated in the remote PostGres container. However, whenever I try to perform my first login by going to 

`http://ingress.local:8001/admin/`

i get a 500 internal server error on a URL redirect of:

`http://ingress.local:8001/admin/api/auth/login?redirect_uri=http%3A%2F%2Fingress.local%3A8001%2Fadmin%2F`

If i create a vanilla virtualbox Ubuntu 21.04 desktop VM and include the server and build tools, then throw the vanilla fief quickstart and everything it needs inside it, working on a browser INSIDE the VM, going to  http://localhost:8000/admin/ **works**. However, this is not particularly useful for me as my evaluation consists of moving auth for a number of existing containerized  apps in *.ingress.local

I'm somewhat familiar with the FastAPI framework and uvicorn/hypercorn, and after exec'ing into the running container, I was able to put uvicorn into debug mode, which spat out the following error stack into docker logs on a repeat of the above event:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 115, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 162, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 159, in _run_app
    return await callback()
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/site-packages/fief/apps/admin/routers/auth.py", line 22, in login
    url = await fief.auth_url(
  File "/usr/local/lib/python3.10/site-packages/fief_client/client.py", line 374, in auth_url
    openid_configuration = await self._get_openid_configuration()
  File "/usr/local/lib/python3.10/site-packages/fief_client/client.py", line 463, in _get_openid_configuration
    response = await client.send(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```
Is there anything obvious that i'm missing before i dive deeper into the code?

Thank you and congratulations for what looks like a very polished SSO experience!

**Comment by shrike71** [comment]
As a matter of course, if i LEAVE OUT the database section so that it uses the sqlite db default in the /data folder, I get the SAME effect

**Comment by frankie567** [comment]
Hi @shrike71! Welcome to Fief!

I understand what's going on, as it's something that I've stumble upon during development. The issue is with I call the "Fief-ception":  the Fief server authenticates users with Fief. That's why we need to set a `FIEF_CLIENT_ID`, `FIEF_CLIENT_SECRET` and `FIEF_BASE_URL`.

What's happening under the hood is that the `/admin/api/auth/login` route will make an HTTP request to retrieve the OpenID metadata (like this: https://fief.fief.dev/.well-known/openid-configuration) to automatically understand how to authenticate users.

The problem here is that we're *inside* the Docker container. Thus, it can't resolve `ingress.local:8001`, as it's something that's wired on your host machine. If we use a real domain like `fief.fief.dev` or if we are on the same localhost and port, it'll work.

I've to say I've not yet found a satisfying solution for this. Something that comes to my mind is to use the `extra_hosts` option of Compose. Could you try something like this:

```yml
version: "3.9"

services:
  fief:
    container_name: fief
    hostname: fief
    image: ghcr.io/fief-dev/fief:latest
    ports:
      - "8001:8001"  # We should map the same port inside/outside
    environment:
      - PORT=8001  # Run Uvicorn on 8001 to match the external port
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_URL=postgresql://postgres:postgres@postgres-eval_db_1:5432/fief
      - SECRET=XXX
      - FIEF_CLIENT_ID=XXX
      - FIEF_CLIENT_SECRET=XXX
      - ENCRYPTION_KEY=XXX
      - FIEF_DOMAIN=ingress.local:8001
      - FIEF_BASE_URL=http://ingress.local:8001
    volumes:
      - fief-server-data:/data
    restart: unless-stopped
    extra_hosts:
        - "ingress.local:127.0.0.1"  # Map ingress.local hostname to localhost inside container
    networks:
      - eval

volumes:
  fief-server-data:
    external: true

networks:
  eval:
    external: true
```

PS: You should avoid to share your SECRET, FIEF_CLIENT_ID, FIEF_CLIENT_SECRET and ENCRYPTION_KEY. Those are highly sensitive values that should be kept secret.

**Comment by shrike71** [comment]
Hi frankie567 and thanks for the prompt reply!

The insight into the metadata method is welcome and awesome! As a matter of fact, I was going to try to hardcode a ref for ingress.local to 127.0.0.1 in the container /etc/hosts file or the "extra_hosts" option myself on Monday, as I was wondering if there was some internal discovery requirement based on 127.0.0.1.

Will post back ASAP if i get to a working solution!

Thanks for the info re the sensitive values, however this is only an experimental server, we would normally use substitution variables, create an .env file and vault based values managed by terraform.

Regards,

Shrike71

**Comment by frankie567** [comment]
> The insight into the metadata method is welcome and awesome! As a matter of fact, I was going to try to hardcode a ref for ingress.local to 127.0.0.1 in the container /etc/hosts file or the "extra_hosts" option myself on Monday, as I was wondering if there was some internal discovery requirement based on 127.0.0.1.

Great! Keep us tuned 🙂

> Thanks for the info re the sensitive values, however this is only an experimental server, we would normally use substitution variables, create an .env file and vault based values managed by terraform.

I thought so, but I prefer to be remind it, just in case 🙂

**Comment by shrike71** [comment]
Some progress... 

I can now see this on navigating to `http://ingress.local:8001/admin/`

![image](https://user-images.githubusercontent.com/748514/164969388-32b50bdc-b915-4c6e-8578-ad7940e3dbf0.png)

I thought that this entry in the _fief_clients.redirects_ column might be a problem, 

`["https://ingress.local:8001/admin/api/auth/callback", "http://localhost:8000/docs/oauth2-redirect", "https://ingress.local:8001/admin/api/auth/callback"]`

so i changed it to 

`["http://ingress.local:8001/admin/api/auth/callback", "http://localhost:8000/docs/oauth2-redirect", "http://ingress.local:8001/admin/api/auth/callback"]`

so as to correct the scheme on the URL to http throughout. However this did not make a difference. Might OpenID be objecting to an http scheme on a non-localhost  URL? I will try a self-signed cert next

**Comment by frankie567** [comment]
Ha, I think I know why! Could you try to set the following environment variables:

```yml
- CSRF_COOKIE_SECURE=False
- LOGIN_SESSION_COOKIE_SECURE=False
- SESSION_COOKIE_SECURE=False
- FIEF_ADMIN_SESSION_COOKIE_SECURE=False
```

By default, those settings are set to `True`: the browser will only save and send the cookie over a SSL connection (which is *highly* recommended in production). However, in local, we usually don't have SSL setup.

In recent versions of Chrome and Firefox, they *relax* this constraint a bit for `localhost` hosts. However, with your custom `ingress.local`, you fall into the general case.

The other solution, as you've suggested, is to setup a proper SSL in local.

Sorry for the clumsy experience so far, but your feedback is greatly appreciated and will help us to improve :)

**Comment by shrike71** [comment]
Ok, after adding in the env pairs above, the experience on going to 

I can now see this on navigating to http://ingress.local:8001/admin/

![Screenshot 2022-04-24 125440](https://user-images.githubusercontent.com/748514/164975351-f2fd3bdd-bca0-4986-8b34-86d5d70458bb.png)

Which i remember was an effect of the installed defaults in column _fief_clients.redirects_. This time, i merely added the "http://ingress.local:8001/admin/api/auth/callback" entry to the JSON array, and it's all working!

![image](https://user-images.githubusercontent.com/748514/164975498-1f313da9-828a-43ff-bef2-25e0303c0f3e.png)

Can't wait to start exploring it now....

Thank you and keep up the good work!

**Comment by frankie567** [comment]
Great to hear!

So to sum up, there is three things needing improvement:

* Routing from *inside* the Docker container
* Secure cookies setting when in local
* Default redirect URI not generated correctly (http/https confusion)
